apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: checkout-httpso
  namespace: ca1
spec:
  hosts:
    - keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  pathPrefixes:
    - /checkout
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkout
    service: checkout-svc
    port: 80
  replicas:
    min: 0
    max: 5
  scaledownPeriod: 30
  targetPendingRequests: 10
